# Feature Importance

In [1]:
import pandas as pd
import numpy as np

# Filepath for dataset
fpath = '/Users/David/Documents/IPython_Notebooks/IntroDS/Term Project/Data_Fit/'

# Upload test dataset to fit & check modeling code
#data=pd.read_csv(fpath + 'clean_sample.csv')

# Upload FINAL dataset for fitting
data=pd.read_csv(fpath + 'clean_master.csv', index_col = 0)

data.head(10)

,year,pit_hand_cd,bat_hand_cd,pa_ball_ct,pa_strike_ct,outs_ct,pitch_type,n-1_pitch_type,n-2_pitch_type,n-3_pitch_type,...,Months,score_position,isMiss_n-1_pit_type,isMiss_n-2_pit_type,isMiss_n-3_pit_type,isMiss_n-1_pit_resut,isMiss_n-2_pit_resut,isMiss_n-3_pit_resut,isMiss_pit_feat,isMiss_bat_feat
0,2014,1,0,0,0,0,1.0,9.0,9.0,9.0,...,3,0,1,1,1,1,1,1,0,0
1,2014,1,0,1,0,0,1.0,1.0,9.0,9.0,...,3,0,0,1,1,1,1,1,0,0
2,2014,1,0,2,0,0,1.0,1.0,1.0,9.0,...,3,0,0,0,1,0,0,1,0,0
3,2014,1,1,0,0,0,1.0,9.0,9.0,9.0,...,3,0,1,1,1,1,1,1,0,0
4,2014,1,1,1,0,0,2.0,1.0,9.0,9.0,...,3,0,0,1,1,1,1,1,0,0
5,2014,1,1,2,0,0,3.0,2.0,1.0,9.0,...,3,0,0,0,1,0,0,1,0,0
6,2014,1,1,3,0,0,1.0,3.0,2.0,1.0,...,3,0,0,0,0,0,0,0,0,0
7,2014,1,1,3,1,0,1.0,1.0,3.0,2.0,...,3,0,0,0,0,0,0,0,0,0
8,2014,1,1,3,2,0,1.0,1.0,1.0,3.0,...,3,0,0,0,0,0,0,0,0,0
9,2014,1,0,0,0,1,1.0,9.0,9.0,9.0,...,3,0,1,1,1,1,1,1,0,0

In [2]:
import sys
sys.path.append('C:/Users/David/Documents/IPython_Notebooks/IntroDS/utils')
import course_utils as bd

# Split master dataset into modeling & final testing subsets
model_data = data[(data['year'] != 2016)]
test_data = data[data['year'] == 2016]

# Drop columns 'year' & 'Months'
model_data = model_data.drop(['year', 'Months'], 1)
test_data = test_data.drop(['year', 'Months'], 1)

train, test = bd.trainTest(model_data, 0.8)
lab = 'pitch_type'

print('Training(model) sample size: ', len(train))
print('Testing(model) sample size: ', len(test))

Training(model) sample size:  1144288
Testing(model) sample size:  286073

In [ ]:
from sklearn.ensemble import RandomForestClassifier

n_est = 100
m_feat = None
sample_split = 300
max_d = 20

rf_best = RandomForestClassifier(criterion='entropy', n_estimators=n_est, n_jobs = -1, max_features=m_feat, 
                                    max_depth=max_d, min_samples_split=sample_split)
rf_best = rf_best.fit(train.drop(lab, 1), train[lab])
       
rf_fi = rf_best.feature_importances_
print(rf_fi)

#print("%d Est / %d Max Feat 'test' Accuracy = %.7f" % (n, m, rf_pred_test))
#print("%d Est / %d Max Feat 'train' Accuracy = %.7f\n" % (n, m, rf_pred_train))